In [3]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Propriedades do ndArray
# Quantas dimensões tem
arr1.ndim

2

In [7]:
# A quantidade de elementos por dimensão
arr1.shape

(2, 3)

In [8]:
# O tipo de dados do ndArray
arr1.dtype

dtype('int32')

In [1]:
# Criar Array só com zeros ou ums

In [4]:
arr2 = np.zeros(10)

In [5]:
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Pode fazer multidimensional

In [6]:
arr3 = np.zeros((4, 4))

In [7]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
arr4 = np.ones((4, 4))

In [9]:
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr5 = np.arange(15)

In [11]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Converte uma lista para ndArray

In [19]:
np.asarray([1, 2, 3])

array([1, 2, 3])

In [20]:
# Gera um ndarray só de ums com o mesmo formato e tipo do array passado

In [26]:
arr6 = np.ones_like([[1, 2, 3], [4, 5, 6]])

In [22]:
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
# Gera uma matriz identidade

In [25]:
arr7 = np.identity(10)

In [27]:
arr7

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])